apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-online
  namespace: amq-online
spec:
  channel: stable
  installPlanApproval: Automatic
  name: amq-online
  source: redhat-operators
  sourceNamespace: openshift-marketplace