---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: enmasse.io:schema
  labels:
    app: enmasse
rules:
  - apiGroups: [ "enmasse.io" ]
    resources: [ "addressspaceschemas" ]
    verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "enmasse.io:schema"
  labels:
    app: enmasse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: enmasse.io:schema
subjects:
- kind: Group
  name: system:authenticated
