apiVersion: syndesis.io/v1beta1
kind: Syndesis
metadata:
  name: app
  namespace: fuse-online
spec:
  addons:
    todo:
      enabled: true
    ops:
      enabled: false
    publicApi:
      enabled: true
      routeHostname: tobereplace.com
